databases:
  - name: linda-mama-fullstack
    databaseName: linda-mama-fullstack
    user: linda-mama-fullstack

services:
  - type: web
    name: linda-mama-fullstack
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: linda-mama-fullstack
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false